### PR TITLE
Example DCCRG API update

### PR DESCRIPTION
**Pull request by iljah**

### CODE REVIEW

**Comment by iljah** [comment]
I couldn't find iteration over neighbors anywhere after short browsing, if you point me to such place I can convert it to new api also.

**Comment by tkoskela** [comment]
See here for example https://github.com/tkoskela/vlasiator/blob/650ddbb4f7f985818bb7647dd9958ad29e575fd5/grid.cpp#L1021

**Comment by iljah** [comment]
Thanks, new commit shows also neighbor iteration: https://github.com/tkoskela/vlasiator/pull/7/commits/6e41103c23b3cefc37ee61373e53c40ef0343503

**Comment by iljah** [comment]
In case OpenMP doesn't allow parallelization over auto ranges I also added old style iterator version of for loop. Haven't tested compilation so details may vary...

**Comment by tkoskela** [comment]
Thanks! This looks pretty nice

**Comment by tkoskela** [comment]
Can I still pass user-defined neighborhoods? Like here for example

https://github.com/iljah/vlasiator/blob/6e41103c23b3cefc37ee61373e53c40ef0343503/grid.cpp#L572

**Comment by iljah** [comment]
Oh right I forgot to include that, just give NEAREST_NEIGHBORHOOD_ID to local_cells and others.

**Comment by tkoskela** [comment]
Did you compile the second example? I merged it to this branch https://github.com/tkoskela/vlasiator/tree/dccrg_update and am using an up-to-date dccrg from the fmihpc master branch. Compiler gives errors

grid.cpp:1016:28: error: expected ‘=’ before ‘:’ token
       for (const auto& cell: mpiGrid.local_cells()) {
                            ^
grid.cpp:1046:31: error: expected ‘;’ before end of line
grid.cpp:1046:31: error: expected primary-expression before end of line
grid.cpp:1046:31: error: expected ‘;’ before end of line
grid.cpp:1046:31: error: expected primary-expression before end of line
grid.cpp:1046:31: error: expected ‘)’ before end of line
grid.cpp:1046:31: error: expected primary-expression before end of line
grid.cpp:1016:7: error: invalid type for iteration variable ‘cell’
       for (const auto& cell: mpiGrid.local_cells()) {
       ^
grid.cpp:1046:31: error: expected ‘}’ before end of line
grid.cpp:1046:31: error: expected ‘while’ before end of line
grid.cpp:1046:31: error: expected ‘(’ before end of line
grid.cpp:1046:31: error: expected primary-expression before end of line
grid.cpp:1046:31: error: expected ‘)’ before end of line
grid.cpp:1046:31: error: expected ‘;’ before end of line
grid.cpp:1046:31: error: expected ‘}’ before end of line
grid.cpp: At global scope:
grid.cpp:1046:31: error: expected declaration before end of line

**Comment by iljah** [comment]
Didn't test compilation, as I wrote earlier. Looks like you excluded 
some whitespace from compiler's message because ^ points to for instead 
of :. Are you compiling with new enough C++?

**Comment by tkoskela** [comment]
How new is new enough? Vlasiator is c++11

**Comment by tkoskela** [comment]
I guess github edits out the whitespace, the ^ points to the : on the above line

**Comment by iljah** [comment]
I suspected en.cppreference.com/w/cpp/language/range-for might be 
missing but it's c++11. Actually OMP might not support that so try 
commented out version instead.

**Comment by iljah** [comment]
Yeah looks like you'll have to use old form or "single producer 
tasking pattern" as shown in stackoverflow.com/a/17853547

**Comment by tkoskela** [comment]
Ah, that is a shame. So unless we get an OpenMP 5.0 compliant compiler we can't parallelise range-based loops with OpenMP.

**Comment by iljah** [comment]
I guess not but old style loop doesn't seem that bad:
```
for (
    auto
        iter = mpiGrid.local_cells().begin(),
        end = mpiGrid.local_cells().end();
    iter != end;
    iter++
) { ...
```

**Comment by iljah** [comment]
Or if you have C++17 or later I think you can just use it with e.g. https://en.cppreference.com/w/cpp/algorithm/transform or https://en.cppreference.com/w/cpp/algorithm/reduce
These and OMP probably have the same implementation anyway so should be compatible at least as long as you don't use both simultaneously.

**Pull request closed without merging**
